import { Command } from 'commander';
import { resolve } from 'node:path';
import chalk from 'chalk';
import { loadState, saveState } from '../../config/state.js';
import { loadWorkspaceConfig } from '../../config/workspace-config.js';
import { discoverServices } from '../../config/service-config.js';
import { scanWorkspace } from '../../core/workspace.js';
import * as git from '../../core/git.js';
import { installService, buildService } from '../../core/service.js';
import { readdirSync, existsSync, readFileSync } from 'node:fs';

export const updateCommand = new Command('update')
  .description('Pull latest, reinstall, and rebuild. Defaults to pulling current branch.')
  .argument('[repos...]', 'Repos to update (updates all foundation + common if omitted)')
  .option('--base', 'Switch to baseBranch (from herdy.yaml) before pulling')
  .option('--branch <branch>', 'Switch to a specific branch before pulling')
  .action(async (repoNames: string[], opts) => {
    const state = loadState();
    if (!state.workspacePath) {
      console.log(chalk.red('No workspace linked. Run `herdy link` or `herdy init` first.'));
      return;
    }

    const config = loadWorkspaceConfig();
    const repos = await scanWorkspace(state.workspacePath);

    let targets;
    if (repoNames.length > 0) {
      targets = repos.filter((r) => repoNames.includes(r.config.name) && r.exists);
      const notFound = repoNames.filter((name) => !repos.some((r) => r.config.name === name));
      if (notFound.length > 0) {
        console.log(chalk.red(`Repo(s) not found: ${notFound.join(', ')}`));
        console.log(chalk.gray(`Available: ${repos.map((r) => r.config.name).join(', ')}`));
        return;
      }
    } else {
      const foundationRepos = repos.filter((r) => r.config.group === 'foundation' && r.exists);
      const commonRepos = repos.filter((r) => r.config.group === 'common' && r.exists);
      targets = [...foundationRepos, ...commonRepos];
    }

    const targetBranch = opts.branch || (opts.base ? config.baseBranch : null);
    const branchLabel = targetBranch ? targetBranch : 'current branch';
    console.log(chalk.bold(`\nUpdating ${targets.length} repo(s) (${branchLabel})...\n`));

    let built = 0;
    let failed = 0;

    for (const repo of targets) {
      const repoPath = repo.path;
      console.log(chalk.cyan(`  ${repo.config.name}:`));

      // Fetch and update
      try {
        process.stdout.write(chalk.gray('    Fetching... '));
        await git.fetch(repoPath);
        console.log(chalk.green('done'));

        const currentBranch = await git.getCurrentBranch(repoPath);
        const dirty = await git.isDirty(repoPath);

        if (dirty) {
          process.stdout.write(chalk.gray('    Cleaning up for pull... '));
          // Discard lock file changes (regenerated by npm install)
          await git.discardLockFiles(repoPath);
          // Stash anything remaining (source changes, untracked files)
          const stillDirty = await git.isDirty(repoPath);
          if (stillDirty) {
            await git.stash(repoPath, `herdy: auto-stash before update (on ${currentBranch})`);
            console.log(chalk.green('stashed'));
          } else {
            console.log(chalk.green('done'));
          }
        }

        // Final safety check — if still dirty after stash, abort this repo
        if (await git.isDirty(repoPath)) {
          console.log(chalk.red('    Still has uncommitted changes after stash — skipping pull.'));
          console.log(chalk.red('    Manually commit or discard changes, then retry.'));
          failed++;
          continue;
        }

        // Switch branch only if --base or --branch specified
        if (targetBranch && currentBranch !== targetBranch) {
          process.stdout.write(chalk.gray(`    Checking out ${targetBranch}... `));
          await git.checkout(targetBranch, repoPath);
          console.log(chalk.green('done'));
        }

        const fromInfo = await git.getCommitInfo(repoPath).catch(() => null);
        process.stdout.write(chalk.gray('    Pulling (rebase)... '));
        await git.pullRebase(repoPath);
        console.log(chalk.green('done'));
        const toInfo = await git.getCommitInfo(repoPath).catch(() => null);
        if (fromInfo && toInfo) {
          if (fromInfo.hash === toInfo.hash) {
            console.log(chalk.gray(`    Already up to date (${toInfo.hash}  ${toInfo.date}  ${toInfo.subject})`));
          } else {
            console.log(chalk.gray(`    ${fromInfo.hash}  ${fromInfo.date}  ${fromInfo.subject}`));
            console.log(chalk.green(`    → ${toInfo.hash}  ${toInfo.date}  ${toInfo.subject}`));
          }
        }

        if (dirty) {
          const stillHasStash = await git.hasStash(repoPath);
          if (stillHasStash) {
            console.log(chalk.yellow(`    ⚠ Stashed changes. Run: git -C ${repo.config.name} stash pop`));
          }
        }
      } catch (err: any) {
        console.log(chalk.red(`failed: ${err.message}`));
        failed++;
        continue;
      }

      // Install and build each service
      const currentCommit = await git.getCurrentCommit(repoPath).catch(() => '');
      const services = discoverServices(repoPath, repo.config.name);
      if (!state.builds) state.builds = {};

      // Check if all services are already built at this commit
      const allBuilt = services.every((service) => {
        const buildKey = `${repo.config.name}/${service.path}`;
        const lastBuild = state.builds[buildKey];
        return lastBuild && lastBuild.commit === currentCommit;
      });
      if (allBuilt && services.length > 0) {
        console.log(chalk.gray(`    Already built at ${currentCommit.slice(0, 7)} — skipped`));
        continue;
      }

      for (const service of services) {
        const servicePath = resolve(repoPath, service.path);
        if (!existsSync(resolve(servicePath, 'package.json'))) continue;

        const buildKey = `${repo.config.name}/${service.path}`;
        const lastBuild = state.builds[buildKey];

        // Skip if already built at this commit
        if (lastBuild && lastBuild.commit === currentCommit) {
          continue;
        }

        try {
          process.stdout.write(chalk.gray(`    Installing ${service.path}... `));
          await installService(servicePath);
          console.log(chalk.green('done'));
        } catch (err: any) {
          console.log(chalk.red(`failed: ${err.message}`));
          failed++;
          continue;
        }

        if (!service.buildScript) {
          console.log(chalk.gray(`    Skipping build for ${service.path} (no build script)`));
          continue;
        }

        try {
          process.stdout.write(chalk.gray(`    Building ${service.path}... `));
          await buildService(servicePath, service.buildScript);
          console.log(chalk.green('done'));
          built++;

          // Record build
          state.builds[buildKey] = { commit: currentCommit, builtAt: new Date().toISOString() };
          saveState(state);
        } catch (err: any) {
          console.log(chalk.red(`failed: ${err.message}`));
          failed++;
        }
      }
    }

    console.log('');
    if (failed > 0) {
      console.log(chalk.yellow(`Done. ${built} built, ${failed} failed.`));
    } else {
      console.log(chalk.green(`Done. All ${built} services updated and built successfully.`));
    }

    // Suggest restart if services are running
    const targetNames = targets.map((r) => r.config.name);
    if (repoNames.length > 0) {
      console.log(chalk.gray(`\nTo pick up changes: herdy restart ${targetNames.join(' ')}`));
    } else {
      console.log(chalk.gray('\nTo pick up changes: herdy restart common'));
    }
  });

function hasBuildScript(servicePath: string): boolean {
  const pkgPath = resolve(servicePath, 'package.json');
  if (!existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
    return !!pkg.scripts?.build;
  } catch {
    return false;
  }
}
